# Generated by Django 4.1.4 on 2023-08-25 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_remove_list_user_accountuser_list_accuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='accUser',
        ),
        migrations.DeleteModel(
            name='AccountUser',
        ),
    ]
